import { MemoCard } from "@/types/app"

export const spanishCards: MemoCard[] = [
  {
    id: "1",
    title: "Desayuno",
    front: "Desayuno",
    back: "Breakfast",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "2",
    title: "Almuerzo",
    front: "Almuerzo",
    back: "Lunch",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "3",
    title: "Cena",
    front: "Cena",
    back: "Dinner",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "4",
    title: "Antes",
    front: "Antes",
    back: "Before",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "5",
    title: "Después",
    front: "Después",
    back: "After",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "6",
    title: "Entender",
    front: "Entender Yo entiendo Tú entiendes",
    back: "To understand, I understand, you understand.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "7",
    title: "Hacer",
    front: "Hacer Yo hago Tú haces",
    back: "To do, I do, you do.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "8",
    title: "Poder",
    front: "Poder Yo puedo Tú puedes",
    back: "To be able, I can, you can.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "9",
    title: "Ver",
    front: "Ver Yo veo Tú ves",
    back: "To see, I see, you see.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "10",
    title: "Volver",
    front: "Volver Yo vuelvo Tú vuelves",
    back: "To return, I return, you return.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "11",
    title: "Ir",
    front: "Ir Yo voy Tú vas",
    back: "To go, I go, you go.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "12",
    title: "Decir",
    front: "Decir Yo digo Tú dices",
    back: "To say, I say, you say.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "13",
    title: "Dar",
    front: "Dar Yo doy Tú das",
    back: "To give, I give, you give.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "14",
    title: "Escuchar",
    front: "Escuchar Yo escucho Tú escuchas",
    back: "To listen, I listen, you listen.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "15",
    title: "Ser",
    front: "Ser Yo soy Tú eres",
    back: "To be, I am, you are.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "16",
    title: "Abrir",
    front: "Abrir Yo abro Tú abres",
    back: "To open, I open, you open.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "17",
    title: "Cerrar",
    front: "Cerrar Yo cierro Tú cierras",
    back: "To close, I close, you close.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "18",
    title: "Ver",
    front: "Ver Yo veo Tú ves",
    back: "To see, I see, you see.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
  {
    id: "19",
    title: "Creer",
    front: "Creer Yo creo Tú crees",
    back: "To believe, I believe, you believe.",
    category: "Español",
    level: 0,
    lastPracticeTimestamp: "",
    createdAtTimestamp: "",
    useReversedDefaultView: false,
  },
]
